recipeauth/new/demo/urls.py
from django.urls import path
from demo import views

app_name = "demo"

urlpatterns = [
    path("home/",views.home, name='home'),
    path("details/<int:recipe_id>/",views.details,name='details'),
    path("process/",views.process,name='process'),
    path("reg/",views.reg,name='reg'),
    path("",views.login_info,name='login'),
    path("validate/",views.validate,name='validate'),
    path("logout/",views.logout_info,name='logout'),
]

recipeauth/new/new/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("demo/", include("demo.urls")),
]

recipeauth/new/demo/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser)
# Create your models here.




class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        user = self.create_user( email,password=password, )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True, )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

class Menu(models.Model):
    name = models.CharField(max_length=200)
    ingrediants = models.TextField(max_length=200)
    process = models.TextField(max_length=200)

    def __str__(self):
        return self.name

recipeauth/new/demo/views.py
from django.shortcuts import render,get_object_or_404
from . models import *
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required


# Create your views here.
def reg(request):
    if request.method == 'POST':
        MyUser.objects.create_user(
            email=request.POST["email"],
            password=request.POST["password"],
        )
        return HttpResponseRedirect("/demo/")
    return render(request, "demo/reg.html")


def login_info(request):
    return render(request, 'demo/login_info.html')


def validate(request):
    email = request.POST["email"]
    password = request.POST["password"]
    user = authenticate(request, email=email, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect('/demo/home/')
    else:
        return HttpResponse("<h1>User is not registered<h1>")


def logout_info(request):
    logout(request)
    return HttpResponseRedirect("/demo/")

@login_required(login_url='menu/')
def home(request):
   # import pdb; pdb.set_trace()
    context = Menu.objects.all()
    return render(request, "demo/home.html", {"context": context})

@login_required
def process(request):
    if request.method == 'POST':
        Menu.objects.create(
            name=request.POST["name"],
            ingrediants=request.POST["ingrediants"],
            process=request.POST["process"],
        )
      #  return HttpResponseRedirect(reverse("menu:home"))
        return HttpResponseRedirect("/demo/home/")
    return render(request, "demo/process.html")

@login_required(login_url='demo/')
def details(request, recipe_id):
    con = get_object_or_404(Menu, pk=recipe_id)
    return render(request, "demo/details.html", {"con": con})

recipeauth/new/demo/templates/demo/details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DETAILS PAGE</title>
</head>
<body>
<form>
{% if con %}
      name : {{ con.name }} <br>
      Ingrediants : {{ con.ingredients }}<br>
      Process : {{ con.process }}<br>
{% endif %}
<a href="{% url 'demo:home' %}">Back</a><br>
<a class="btn btn-primary btn-1g" href="{% url 'demo:logout' %}" role="button" > LOGOUT </a>
</form>
</body>

</html>

recipeauth/new/demo/templates/demo/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MENU</title>
</head>
<body>
{% if context %}
    {% for each in context %}
<a href="/demo/details/{{ each.id }}">{{each.name}}</a><br>
    {% endfor %}
{% endif %}
</body>
</html>

<a class="btn btn-primary btn-1g" href="/demo/process/" role="button"> CREATE </a><br>
<a class="btn btn-primary btn-1g" href="{% url 'demo:logout' %}" role="button" > LOGOUT </a>

recipeauth/new/demo/templates/demo/login_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN PAGE</title>
</head>
<body>
<form action="/demo/validate/" method="post">
    {% csrf_token %}
email<input type="email" name="email"><br>
password<input type="password" name="password"><br>
<input type="submit" value="Login"><br>

</form>
    <a href="{% url 'demo:reg' %}">REGISTER</a>
</body>
</html>

recipeauth/new/demo/templates/demo/process.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Process of Recipe</title>
</head>
<body>
<form method='post'>
    {% csrf_token %}

    Name of the Recipe:  <input type="text" name="name"><br>
    Ingrediants:<input type="text" name="ingrediants"><br>
    Process :<input type="text" name="process"><br>
    <input type="submit" value="Save"><br>

</form>
<a class="btn btn-primary btn-1g" href="{% url 'demo:logout' %}" role="button" > LOGOUT </a>
</body>

recipeauth/new/demo/templates/demo/reg.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>REGISTRATION PAGE</title>
</head>
<body>
<form method='post'>
    {% csrf_token %}

    email:  <input type="email" name="email"><br>
    password:<input type="password" name="password"><br>
    <input type="submit" value="Save"><br>

</form>
</body>
</html>